# Generated by Django 4.1.3 on 2023-02-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": [
                    "last_name",
                    "first_name",
                    "date_of_birth",
                    "city",
                    "blood_type",
                ],
                "verbose_name_plural": "Patients",
            },
        ),
    ]
