# Generated by Django 4.1.3 on 2023-02-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
        ("patients", "0002_alter_patient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.doctor",
            ),
        ),
    ]
