# Generated by Django 4.1.3 on 2023-02-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="patients",
        ),
    ]
